version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
