spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank?currentSchema=public&serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 51546EB53E8439F156ACD2A7B7301CADEC13D0FF85F46FF0CC97005AE16776B7
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: DEBUG